In [6]:
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf

In [8]:
x=tf.constant(4.0)
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
y=tf.constant([[1,2,3],[4,5,6]])
print(y.shape)

(2, 3)


In [13]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x=tf.zeros(2,3) #create matrix all zero
print(x)

tf.Tensor([0 0], shape=(2,), dtype=int32)


In [16]:
x=tf.eye(3)  #create identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
x=tf.random.normal((3,3),mean=0,stddev=0)
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [18]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-0.97794956  2.0054207   0.13405737]
 [ 0.11586971 -0.83957577  0.2922889 ]
 [-0.98042226 -1.2464198   1.1004974 ]], shape=(3, 3), dtype=float32)


In [19]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [22]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [28]:
x=4.5
y=tf.cast(x,dtype=tf.float64)
print(y)

tf.Tensor(4.5, shape=(), dtype=float64)


In [30]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])

In [31]:
z=tf.add(x,y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [34]:
z=tf.subtract(x,y)
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [35]:
z=tf.divide(x,y)
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [36]:
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [45]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,5))
print(x)
print(y)


tf.Tensor(
[[-0.46576202 -0.8439353   1.5924757 ]
 [-0.19235891 -0.2697452   0.70468384]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.72753406  0.61503077 -0.14617747  0.57499915 -0.37166488]
 [-1.1612573   0.00651349 -2.1153874  -1.0852351  -0.2606821 ]
 [-0.96722037  0.30396298 -1.1349614  -0.26756594 -0.6229776 ]], shape=(3, 5), dtype=float32)


In [46]:
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[-0.8991066   0.1920987   0.04593575  0.2219632  -0.5989705 ]
 [-0.5082886   0.09413417 -0.20105481 -0.00641862 -0.29719144]], shape=(2, 5), dtype=float32)


In [47]:
import tensorflow as tf

ragged_data = [[1, 2],
               [3, 4, 5],
               [6],
               [7, 8, 9, 10]]
ragged_tensor = tf.ragged.constant(ragged_data)
print("Ragged Tensor:")
print(ragged_tensor)

Ragged Tensor:
<tf.RaggedTensor [[1, 2], [3, 4, 5], [6], [7, 8, 9, 10]]>


In [51]:
import tensorflow as tf
dense_data = [[0, 0, 3, 0],
              [0, 0, 0, 0],
              [0, 2, 0, 0]]
sparse_tensor = tf.sparse.from_dense(dense_data)
print("Sparse Tensor:")
print(sparse_tensor)

Sparse Tensor:
SparseTensor(indices=tf.Tensor(
[[0 2]
 [2 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([3 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
